gnome-keysign/gnome-keysign

README.rst
keysign/scan_barcode.py

The gtksink helps us to remove code dealing with the X window IDs and more. It should also work much more reliably in virtual machines or with GL sinks.
The autovideosrc should work nicely with sandboxed environments like Flatpak.

Use gtksink and autovideosrc instead of xvimagesink and v4l2src

---

README.rst

This is a small change to README.rst
Without the code block the commands in the section "From git" were all displayed in one line.
I added it for every code snippets for consistency.
I also added the "cd gnome-keyring" command for complete the install process.
And fixed the typo from "they" to "the".

Corrected a typo and added 'code' blocks

---

packaging/PKGBUILD
packaging/avoid_monkeysign.patch

The patch file avoid to install two times monkeysign because it is
already declared as dependency in the PKGBUILD.

Update the PKGBUILD for Arch Linux

---

keysign/app.py
keysign/keyfprscan.py
keysign/receive.py

Gst.init() requires a [str] or None as parameters.
On ArchLinux with the package gst-python that is "GStreamer Python
binding overrides (complementing the bindings provided by python-gi)",
leaving init() without parameters causes a runtime error.
Adding `None` as parameter it will works with gst-python and also
without it.

app: Fix Gst.init parameters

---

keysign/gnome-keysign-sign-key.py

encode() is necessary for Python 3 compatibility, otherwise it will
fail with:
"TypeError: arg 2: expected gpg.Data, file, bytes (not string!), or an
object implementing the buffer protocol. Got: str"
I also removed the unused sleep import.

gnome-keysign-sign-key: Add encode() for Python 3 compatibility

---

keysign/util.py

This change has been made because the default MD5 is vulnerable and also
because from Python 3.4, MD5 as implicit default digest for digestmod,
is deprecated.

util: switch hmac digest to sha256

---

keysign/send.py

The function _restart_bluetooth can be called after a transfer ends or
after the user presses the back button (and triggers the closing of the
BT socket).
If the back button has been pressed we don't want to restart the
Bluetooth service.

send: avoid BT restart when back has been pressed

---

tests/test_bluetooth.py
tests/test_gpgmks.py

Bluetooth (bluez) is an optional module, and now, since gpgme is enabled by default, Monkeysign is no more essential for a gnome-keysign installation.
With these "skipUnless" we avoid to fail the nose tests even if these two modules are not installed.

Skip BT and mks tests if the modules aren't available

---

keysign/util.py

If we use Bluetooth as the transfer method the signing process will fail
with the following trace:
```
Traceback (most recent call last):
File "/tmp/gnome-keysign/keysign/receive.py", line 155, in on_sign_key_confirmed
sign_keydata_and_send(keydata))
File "/tmp/gnome-keysign/keysign/util.py", line 127, in sign_keydata_and_send
for uid, encrypted_key in list(sign_keydata_and_encrypt(keydata, error_cb)):
File "/tmp/gnome-keysign/keysign/gpgmeh.py", line 406, in sign_keydata_and_encrypt
ctx.op_import(minimise_key(keydata))
File "/tmp/gnome-keysign/keysign/gpgmeh.py", line 380, in minimise_key
ctx.op_import(keydata)
File "/usr/lib/python2.7/site-packages/gpg/core.py", line 132, in _funcwrap
result = func(slf.wrapped, *args)
TypeError: arg 2: expected gpg.Data, file, or an object implementing …
```

util: fix TypeError when we try to sign with Bluetooth

---

setup.py

Without the xml declaration the flatpak build fails.

Add missing xml declaration for the appdata translation

---

data/org.gnome.Keysign.raw.appdata.xml
setup.py

This PR contains a fix for this issue https://github.com/hughsie/appstream-glib/issues/209#issuecomment-388020119 and, following the appstream specs, now the appdata file is stored inside `share/metainfo` instead of `share/appdata`

Double appdata fixes

---

keysign/receive.py
keysign/util.py

`bus.get_object` is a blocking call that in rare cases can take a long
time to complete leading to a very long startup time.
Calling this function with a deferred thread solves this problem.
I faced this issue with an Ubuntu VM. This was the output:
```
org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
```

Check for Bluetooth availability with a deferred thread

---

keysign/bluetoothoffer.py

Because we already found the mac address of the Bluetooth adapter we are
going to use, it makes sense to bind the socket with exactly this
address instead of the generic BDADDR_ANY.
Also with Flatpak apparently the constant BDADDR_ANY is not available,
so this change is required in order to use Bluetooth inside Flatpak.

bluetoothoffer: bind only with the BT address we have in the system

---

setup.py

The former pep8 has been recently renamed to pycodestyle.
https://github.com/PyCQA/pycodestyle/blob/82a2408c0c097d99d6ecfe13e876cdb77f37e112/README.rst

setup: update old pep8 to pycodestyle

---

keysign/util.py

I had to duplicate the body because we can't do something like:
original = "hello"
translated = _(original)
Because gettext supports just string literals.

Compose the email in english alongside the translation

---

keysign/bluetoothoffer.py
keysign/offer.py

This fix is related to the PR #52
Now we defer `get_local_bt_address` to a different thread. In this way
we don't stall the UI waiting for this method reply.

Allocate Bluetooth code with inlineCallbacks

---

README.rst
keysign/network/AvahiBrowser.py
keysign/network/AvahiConstants.py
keysign/network/AvahiPublisher.py
packaging/gnome-keysign.spec

python-avahi is a package that just provides some constants. The problem
we were facing is that Debian is currently providing only python2-avahi
and not pytho3-avahi
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853239
With this commit we simply ship ourselves the Avahi constants we need,
like Gajim already did
https://dev.gajim.org/gajim/gajim/merge_requests/255
In AvahiBrowser there were also two unused imports (DBusException and
Gio), so I used this opportunity to remove them.

Replace python-avahi with a vendorized version

---

keysign/wormholeoffer.py

With the recent wormhole versions (probably from the 0.11.0) the close()
behaviour slightly changed.
In keysign output we got this message when we cancelled a pending
sending operation:
```
Unhandled error in Deferred:
Traceback (most recent call last):
Failure: wormhole.errors.LonelyError:
```
To solve this I added an error callback to the close function. Because
we still catch every possible errors in the start() function, here I
just redirect the error output to `log.debug`.

wormholeoffer: prevent unhandled LonelyError

---

setup.py

This is required to make the build reproducible since `os.walk()` delivers entries in non-specified order. (Upstreaming Debian patch https://salsa.debian.org/debian/gnome-keysign/commit/79552bfcb7880273b4b59c035bc42317c7c4e06f#725acc599c92eccc98708b484af46143e3bba690)

provide pofiles in order

---

data/gnome-keysign-sign-key.man.rst

The CLI tool that we install is called gnome-keysign-sign-key.
With this commit we point the man page to the correct place.

Rename gks-sign-key man page to gnome-keysign-sign-key

---

keysign/util.py

With urllib3 newer than 1.22 it breaks:
urllib3.util.parse_url("http://[[127.1]]")
/tmp/gks3/lib/python3.6/site-packages/urllib3/util/url.py in
parse_url(url)
399
400     except (ValueError, AttributeError):
--> 401         return six.raise_from(LocationParseError(source_url),
None)
402
403     # For the sake of backwards compatibility we put empty
/tmp/gks3/lib/python3.6/site-packages/urllib3/packages/six.py in
raise_from(value, from_value)
LocationParseError: Failed to parse: http://[[127.1]]

util: Use brackets for IPv6 addresses, only

---

keysign/keylistwidget.py
keysign/send.py
keysign/send.ui
keysign/sign_and_encrypt.py
tests/create_attestee.sh
tests/create_attestor.sh

This lays the foundation for being able to return the signature we have received to where it has come from.
It doesn't work just yet, though.
The way I test this is to run the `create_attestee.sh` and attestor scripts, then `env "GNUPGHOME=/tmp/gks-attestor" python3 -m keysign.sign_and_encrypt /tmp/gks-attestee/attestee.pgp.asc`, and finally `env "GNUPGHOME=/tmp/gks-attestee" python3 -m keysign.send`. Then, I can drag and drop the generated file. After one run, I run `env "GNUPGHOME=/tmp/gks-attestee" gpg --edit-key atte` "minimize" "save" to have a clean state.

Add a return certification button

---

keysign/gpgmeh.py
keysign/keyconfirm.py
keysign/receive.py
keysign/receive.ui

This shows an infobar if something went wrong.
Additionally, it pops up a modal dialog (sorry) with the details of the error. Not that it would help, because details are scarce, but I think we can't do any better for now.
Translating those strings would be nice, but.. I guess the proper solution is to define the dialog in the UI file rather than pulling `_` into the keyconfirm module.

Handle receive error more gracefully

---

keysign/app.py

Python 3.12 warns about invalid escape sequences.
'[\s]+' contains an invalid escape sequence.  Python just treats it as a literal backslash followed by an s, but (for example) '[\n]+' would behave differently.
We fix this by telling python to treat the string as "raw" -- that is, not to escape the sequence at all.  This lets the regular expressions module see the backslash directly, as intended.

Avoid SyntaxWarning with Python 3.12
